server:
  port: 4000
minio:
  url: http://117.72.14.166:9000
  accessKey: minioadmin
  secretKey: minioadmin
storage:
  service:
    type: minio
nacos:
  config:
    secret-key: nacos
    access-key: nacos
    data-id: jc-club-oss
    group: DEFAULT_GROUP
    type: yaml
    server-addr: http://117.72.14.166:8848/
    auto-refresh: true
    remote-first: true
    bootstrap:
      enable: true
